"""
This is a pilot file for the project.
We are making a Value Stream Mapping toolbox with the following features:
OBJECTIVES: 
    1) Mimic a volkswagen OEM(Original Equipment Manufacturer) assembly line
    2) Create a GUI for the user to interact with the assembly line by changing the parameters of the line
    3) Create a simulation of the assembly line
    4) Have a dahsboard to edit the parameters of each robot in the assembly line
    5) Have predefined robots that can be added to the assembly line
    6) Have Predefined states that the robots can be in so that the user can easily add robots to the assembly line
    7) 6 Will also help us demonstrate the predictive alerts that can be generated by the system
    8) Create a separate alert system that will alert the user of any issues in the assembly line
    9) Have a VSM Graph that will show the user the current state of the assembly line
    10) In the Graph show predictions of the future state of the assembly line by predicting the state of the robots

The project will be divided into the following modules:
    1) Assembly Line
    2) Processes
    3) Robots
    4) States
    5) Alerts
    6) VSM Graph
    7) Dashboard
    8) Controller Module

    ** We add processes to the assembly line with each process having a set of robots that will perform the process

Since we might have to host the project on a server, we will be using Flask to create the GUI

Phase I: Backend
-[] Create the Processes
-[x] Create the Robots
-[] Create Assembly Line
-[] Create the States for the Robots
-[] Create the Controller Module
-[] Create the Alerts with proper triggers that come from the Controller Module
"""

"""
FOLDER STRUCTURE

volkswagen-vsm/
├── pilot.py
├── app/
│   ├── __init__.py
│   ├── assembly_line/
│   │   ├── __init__.py
│   │   └── assembly_line.py
│   ├── robots/
│   │   ├── __init__.py
│   │   └── robots.py
│   ├── states/
│   │   ├── __init__.py
│   │   └── states.py
│   ├── alerts/
│   │   ├── __init__.py
│   │   └── alerts.py
│   ├── processes/
│   │   ├── __init__.py
│   │   └── processes.py
│   ├── vsm_graph/
│   │   ├── __init__.py
│   │   └── vsm_graph.py
│   ├── dashboard/
│   │   ├── __init__.py
│   │   └── dashboard.py
├── utils/
│   ├── __init__.py
│   └── utils.py(metrics, etc)
│   └── controller/
│       ├── __init__.py
│       └── controller.py
├── static/
│   └── css/
│       └── styles.css
├── templates/
│   ├── base.html
│   ├── index.html
│   └── dashboard.html
├── requirements.txt
└── run.py
"""

"""
A typical Assembly Line will have the following processes and respective robots:
1) Welding Process
    - Welding Robot
    - Inspection Robot
    - Cleaning Robot
2) Painting Process
    - Painting Robot
    - Inspection Robot
    - Drying Robot

We will create the above processes and robots in the respective modules
We need to provide some predefined processes and robots that the user can add to the assembly line
and also provide the user with the ability to create custom processes and robots
"""